version: '3.8'
services:
  db:
    image: postgres:16
    container_name: accesia-db
    restart: always
    environment:
      - POSTGRES_DB=accesia_dev
      - POSTGRES_USER=accesia_user
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
